import { Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from './ReduxProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Star Tech',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang='en'>
        <body
          className={`${inter.className} min-h-screen bg-background text-black`}
        >
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
